/*
 * SPDX-License-Identifier: AGPL-3.0-only
 * Copyright (c) 2022-2026, daeuniverse Organization <dae@v2raya.org>
 *
 * Tests of the optional "ech_tunnel" config section.
 */

package config

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/daeuniverse/dae/pkg/config_parser"
)

func parseSections(t *testing.T, content string) *Config {
	t.Helper()
	sections, err := config_parser.Parse(content)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	conf, err := New(sections)
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	return conf
}

func TestEchTunnelSectionAbsent(t *testing.T) {
	conf := parseSections(t, `global{} routing{}`)
	if conf.EchTunnel != nil {
		t.Fatalf("EchTunnel = %+v, want nil", conf.EchTunnel)
	}
	// Marshaling a config without the section must not emit it.
	b, err := conf.Marshal(2)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(b), "ech_tunnel") {
		t.Fatalf("marshal emitted ech_tunnel for nil section:\n%s", b)
	}
}

func TestEchTunnelSectionParse(t *testing.T) {
	conf := parseSections(t, `
global{}
routing{}
ech_tunnel {
    listen: '127.0.0.1:1080'
    server: 'your-worker.workers.dev:443/tunnel'
    ip: '104.21.16.1'
    token: 'secret-token'
    dns: 'dns.alidns.com/dns-query'
    ech_domain: 'cloudflare-ech.com'
}
`)
	want := &EchTunnel{
		Listen:    "127.0.0.1:1080",
		Server:    "your-worker.workers.dev:443/tunnel",
		ServerIP:  "104.21.16.1",
		Token:     "secret-token",
		DNSServer: "dns.alidns.com/dns-query",
		EchDomain: "cloudflare-ech.com",
	}
	if !reflect.DeepEqual(conf.EchTunnel, want) {
		t.Fatalf("EchTunnel = %+v, want %+v", conf.EchTunnel, want)
	}
}

func TestEchTunnelSectionServerRequired(t *testing.T) {
	sections, err := config_parser.Parse(`
global{}
routing{}
ech_tunnel {
    listen: '127.0.0.1:1080'
}
`)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := New(sections); err == nil {
		t.Fatal("expected error when ech_tunnel has no server")
	} else if !strings.Contains(err.Error(), "server") {
		t.Fatalf("error = %v, want server validation error", err)
	}
}

func TestEchTunnelSectionUnknownKey(t *testing.T) {
	sections, err := config_parser.Parse(`
global{}
routing{}
ech_tunnel {
    server: 'a:443'
    nope: 1
}
`)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := New(sections); err == nil {
		t.Fatal("expected error for unknown key")
	}
}

func TestEchTunnelSectionMarshalRoundTrip(t *testing.T) {
	conf := parseSections(t, `
global{}
routing{}
ech_tunnel {
    listen: '127.0.0.1:1080'
    server: 'w.example.com:443/tunnel'
    token: 'tok'
}
`)
	b, err := conf.Marshal(2)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(b), "ech_tunnel") {
		t.Fatalf("marshal dropped the ech_tunnel section:\n%s", b)
	}
	// Re-parse the marshaled config and compare.
	conf2 := parseSections(t, string(b))
	if !reflect.DeepEqual(conf.EchTunnel, conf2.EchTunnel) {
		t.Fatalf("round trip mismatch:\n%+v\n%+v", conf.EchTunnel, conf2.EchTunnel)
	}
}

func TestEchTunnelInOutline(t *testing.T) {
	out := ExportOutline("test")
	for _, section := range out.Structure {
		if section.Mapping == "ech_tunnel" {
			if len(section.Structure) == 0 {
				t.Fatal("ech_tunnel outline has no children")
			}
			keys := map[string]bool{}
			for _, child := range section.Structure {
				keys[child.Mapping] = true
			}
			for _, want := range []string{"listen", "server", "ip", "token", "dns", "ech_domain"} {
				if !keys[want] {
					t.Errorf("outline of ech_tunnel misses key %q", want)
				}
			}
			return
		}
	}
	t.Fatal("ech_tunnel section missing from exported outline")
}

// TestLuCIGeneratedRunfile feeds the exact fragment produced by the LuCI
// page (luci-app-daed ech.lua build_runfile) through the real dae parser,
// guarding the UI -> config contract.
func TestLuCIGeneratedRunfile(t *testing.T) {
	const generated = `# Generated by luci-app-daed (ECH Tunnel). Do not edit manually.

ech_tunnel {
    listen: '127.0.0.1:1080'
    server: 'your-worker.workers.dev:443/tunnel'
    ip: '104.21.16.1'
    token: 'secret'
    dns: 'dns.alidns.com/dns-query'
    ech_domain: 'cloudflare-ech.com'
}

node {
    ech-node: 'echws://your-worker.workers.dev:443/tunnel?ip=104.21.16.1&token=secret'
}

group {
    ech_tunnel {
        filter: name(ech-node)
        policy: min_moving_avg
    }
}
`
	// The fragment is an include snippet: merge it the way the daemon does.
	dir := t.TempDir()
	fragment := filepath.Join(dir, "ech_tunnel.dae")
	if err := os.WriteFile(fragment, []byte(generated), 0600); err != nil {
		t.Fatal(err)
	}
	entry := filepath.Join(dir, "entry.dae")
	entryContent := "include { ech_tunnel.dae }\nglobal {}\nrouting {}\n"
	if err := os.WriteFile(entry, []byte(entryContent), 0600); err != nil {
		t.Fatal(err)
	}
	sections, _, err := NewMerger(entry).Merge()
	if err != nil {
		t.Fatalf("merge LuCI generated runfile: %v", err)
	}
	conf, err := New(sections)
	if err != nil {
		t.Fatalf("config.New on LuCI generated runfile: %v", err)
	}
	if conf.EchTunnel == nil ||
		conf.EchTunnel.Listen != "127.0.0.1:1080" ||
		conf.EchTunnel.Server != "your-worker.workers.dev:443/tunnel" ||
		conf.EchTunnel.ServerIP != "104.21.16.1" ||
		conf.EchTunnel.Token != "secret" {
		t.Fatalf("ech_tunnel = %+v", conf.EchTunnel)
	}
	if len(conf.Node) != 1 {
		t.Fatalf("node entries = %d, want 1", len(conf.Node))
	}
	// KeyableString keeps the tag: "tag:link".
	wantLink := "ech-node:echws://your-worker.workers.dev:443/tunnel?ip=104.21.16.1&token=secret"
	if string(conf.Node[0]) != wantLink {
		t.Fatalf("node link = %v, want %v", string(conf.Node[0]), wantLink)
	}
	if len(conf.Group) != 1 || conf.Group[0].Name != "ech_tunnel" {
		t.Fatalf("groups = %+v", conf.Group)
	}
}

// TestLuCIGeneratedGistRunfile feeds the gist-sync fragment produced by the
// LuCI page (ech_sub.dae) through the real dae parser.
func TestLuCIGeneratedGistRunfile(t *testing.T) {
	generated := "# Generated by luci-app-daed (ECH Tunnel, gist sync). Do not edit manually.\n\nsubscription {\n    ech_nodes: 'gist-file://tok123@abc123def456/nodes.json'\n}\n"
	// The fragment is an include snippet; merge it like the daemon does.
	dir := t.TempDir()
	fragment := filepath.Join(dir, "ech_sub.dae")
	if err := os.WriteFile(fragment, []byte(generated), 0600); err != nil {
		t.Fatal(err)
	}
	entry := filepath.Join(dir, "entry.dae")
	entryContent := "include { ech_sub.dae }\nglobal {}\nrouting {}\n"
	if err := os.WriteFile(entry, []byte(entryContent), 0600); err != nil {
		t.Fatal(err)
	}
	sections, _, err := NewMerger(entry).Merge()
	if err != nil {
		t.Fatalf("merge: %v", err)
	}
	conf, err := New(sections)
	if err != nil {
		t.Fatalf("config.New: %v", err)
	}
	if len(conf.Subscription) != 1 {
		t.Fatalf("subscriptions = %v", conf.Subscription)
	}
	want := "ech_nodes:gist-file://tok123@abc123def456/nodes.json"
	if got := string(conf.Subscription[0]); got != want {
		t.Fatalf("subscription = %q, want %q", got, want)
	}
}
