//go:build dae_stub_ebpf

/*
 * SPDX-License-Identifier: AGPL-3.0-only
 * Copyright (c) 2022-2026, daeuniverse Organization <dae@v2raya.org>
 *
 * Behaviour tests for the ech_tunnel drop-in fragments of the dashboard build:
 * the section written by the LuCI "ECH Tunnel" page must reach the core config
 * that the daemon hands to the control plane, while everything else in the
 * fragments is ignored and unsafe files are refused.
 *
 * Not part of the patch -- a maintenance fixture for verifying it against a
 * wing revision bump. From a checkout of the pinned wing revision with the
 * patchset applied:
 *
 *	cp ../patchset/tests/wing-ech-tunnel-fragments_test.go dae/
 *	GOOS=linux GOARCH=amd64 go test -tags dae_stub_ebpf ./dae/ -run TestEchTunnelFragment -v
 */

package dae

import (
	"os"
	"path/filepath"
	"testing"

	daeConfig "github.com/corevie/dae/config"
	"github.com/corevie/dae/pkg/config_parser"
)

// newConfig builds the baseline the dashboard produces: global/dns/routing
// from the database, with no ech_tunnel section at all.
func newConfig(t *testing.T) *daeConfig.Config {
	t.Helper()
	conf, err := daeConfig.New(mustParse(t, "global {}\ndns {}\nrouting { fallback: direct }\n"))
	if err != nil {
		t.Fatalf("baseline config: %v", err)
	}
	if conf.EchTunnel != nil {
		t.Fatal("baseline unexpectedly has an ech_tunnel section")
	}
	return conf
}

func mustParse(t *testing.T, text string) []*config_parser.Section {
	t.Helper()
	sections, err := config_parser.Parse(text)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	return sections
}

func writeFragment(t *testing.T, dir, name, content string, perm os.FileMode) string {
	t.Helper()
	path := filepath.Join(dir, name)
	if err := os.WriteFile(path, []byte(content), perm); err != nil {
		t.Fatalf("write fragment: %v", err)
	}
	// os.WriteFile honours umask; make the mode deterministic.
	if err := os.Chmod(path, perm); err != nil {
		t.Fatalf("chmod fragment: %v", err)
	}
	return path
}

const tunnelFragment = `
# Generated by luci-app-daed (ECH Tunnel). Do not edit manually.

ech_tunnel {
    listen: '127.0.0.1:1080'
    server: 'your-worker.workers.dev:443/tunnel'
    ip: '104.21.16.1'
    token: 'e2659947'
    dns: 'dns.alidns.com/dns-query'
    ech_domain: 'cloudflare-ech.com'
}
`

func TestEchTunnelFragmentsMerged(t *testing.T) {
	dir := t.TempDir()
	writeFragment(t, dir, "ech_tunnel.dae", tunnelFragment, 0600)
	conf := newConfig(t)

	if err := MergeEchTunnelFragments(conf, dir); err != nil {
		t.Fatalf("merge: %v", err)
	}
	if conf.EchTunnel == nil {
		t.Fatal("the ech_tunnel section did not reach the config")
	}
	want := daeConfig.EchTunnel{
		Listen:    "127.0.0.1:1080",
		Server:    "your-worker.workers.dev:443/tunnel",
		ServerIP:  "104.21.16.1",
		Token:     "e2659947",
		DNSServer: "dns.alidns.com/dns-query",
		EchDomain: "cloudflare-ech.com",
	}
	if *conf.EchTunnel != want {
		t.Fatalf("EchTunnel = %+v, want %+v", *conf.EchTunnel, want)
	}
}

func TestEchTunnelFragmentsAbsentIsNoop(t *testing.T) {
	dir := t.TempDir()
	conf := newConfig(t)
	if err := MergeEchTunnelFragments(conf, dir); err != nil {
		t.Fatalf("merge: %v", err)
	}
	if conf.EchTunnel != nil {
		t.Fatal("an empty directory must not add a tunnel")
	}
}

// Only ech_tunnel is read: a fragment cannot smuggle routing/global overrides
// past the database, which stays authoritative.
func TestEchTunnelFragmentsIgnoreOtherSections(t *testing.T) {
	dir := t.TempDir()
	writeFragment(t, dir, "sneaky.dae", `
global { log_level: 'trace' }
routing { fallback: block }
subscription { sub: 'https://example.com/sub' }
ech_tunnel {
    listen: '127.0.0.1:1080'
    server: 'host:443'
}
`, 0600)
	conf := newConfig(t)
	before := conf.Global.LogLevel

	if err := MergeEchTunnelFragments(conf, dir); err != nil {
		t.Fatalf("merge: %v", err)
	}
	if conf.EchTunnel == nil || conf.EchTunnel.Server != "host:443" {
		t.Fatalf("ech_tunnel not merged: %+v", conf.EchTunnel)
	}
	if conf.Global.LogLevel != before {
		t.Fatalf("a fragment overrode global config: %v -> %v", before, conf.Global.LogLevel)
	}
	if len(conf.Subscription) != 0 {
		t.Fatalf("a fragment injected subscriptions: %+v", conf.Subscription)
	}
}

// A tunnel definition any local user could rewrite must not be loaded.
func TestEchTunnelFragmentsRefuseWorldWritable(t *testing.T) {
	dir := t.TempDir()
	writeFragment(t, dir, "ech_tunnel.dae", tunnelFragment, 0666)
	conf := newConfig(t)

	if err := MergeEchTunnelFragments(conf, dir); err != nil {
		t.Fatalf("merge: %v", err)
	}
	if conf.EchTunnel != nil {
		t.Fatal("a world-writable fragment was loaded")
	}
}

// A malformed fragment is reported, not fatal: the rest of the config still
// loads and the tunnel is simply absent.
func TestEchTunnelFragmentsMalformedIsSkipped(t *testing.T) {
	dir := t.TempDir()
	writeFragment(t, dir, "broken.dae", "ech_tunnel { this is not a section", 0600)
	conf := newConfig(t)

	if err := MergeEchTunnelFragments(conf, dir); err != nil {
		t.Fatalf("a malformed fragment must not fail the merge: %v", err)
	}
	if conf.EchTunnel != nil {
		t.Fatal("a malformed fragment produced a tunnel config")
	}
}

// Two fragments declaring the section are ambiguous: report an error so the
// daemon logs it instead of silently picking one.
func TestEchTunnelFragmentsDuplicateIsReported(t *testing.T) {
	dir := t.TempDir()
	writeFragment(t, dir, "a.dae", "ech_tunnel {\n    server: 'a:443'\n}\n", 0600)
	writeFragment(t, dir, "b.dae", "ech_tunnel {\n    server: 'b:443'\n}\n", 0600)
	conf := newConfig(t)

	if err := MergeEchTunnelFragments(conf, dir); err == nil {
		t.Fatal("expected an error for duplicate sections")
	}
	if conf.EchTunnel != nil {
		t.Fatal("no tunnel should be applied from ambiguous fragments")
	}
}

// The LuCI page may write an invalid combination (no server); it must be
// reported rather than producing a half-configured tunnel.
func TestEchTunnelFragmentsServerRequired(t *testing.T) {
	dir := t.TempDir()
	writeFragment(t, dir, "ech_tunnel.dae", "ech_tunnel {\n    listen: '127.0.0.1:1080'\n}\n", 0600)
	conf := newConfig(t)

	if err := MergeEchTunnelFragments(conf, dir); err == nil {
		t.Fatal("expected an error when server is missing")
	}
	if conf.EchTunnel != nil {
		t.Fatal("no tunnel should be applied without a server")
	}
}

// The default directory is where the LuCI page writes; pin it so a change on
// either side is noticed.
func TestEchTunnelFragmentDirDefault(t *testing.T) {
	if EchTunnelFragmentDir != "/etc/daed" {
		t.Fatalf("EchTunnelFragmentDir = %q, want /etc/daed", EchTunnelFragmentDir)
	}
}
